config/routes.rb
Shouter::Application.routes.draw do
  root to: "welcome#index"
  resource :dashboard, only: [:show]
  resources :shouts, only: [:create, :show]
  resources :users, only: [:show] do
    resources :following_relationships, only: [:create]
  end
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  delegate :email, to: :user, prefix: true

  def self.current
    order("created_at DESC")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :shouts
  has_many :following_relationships, foreign_key: :follower_id
  has_many :followed_users, through: :following_relationships

  def current_shouts
    shouts.current
  end

  def follow(followed_user)
    followed_users << followed_user
  end

  def can_follow?(followed_user)
    followed_users.includes? followed_user && followed_user != email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_filter :authorize

  def show
    @shout = Shout.new
    @shouts = current_user.shouts.current
  end

end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  def create
    followed_user = User.find(params[:user_id])
    current_user.follow(followed_user)
    redirect_to followed_user, notice: "Now following #{followed_user.email}"
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController

  before_filter :authorize, only: [:create]

  def create
    @shout = current_user.shouts.new(params[:shout])
    @shout.save
    redirect_to dashboard_path
  end

  def show
    @shout = Shout.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @shouts = @user.current_shouts
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :redirect_to_dashboard_when_authenticated

  def index
    @user = User.new
  end

  private
  def redirect_to_dashboard_when_authenticated
   redirect_to dashboard_path if signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
Welcome <%= current_user.email %>

<%= form_for(@shout) do |form| %>
  <%= form.text_field :body, placeholder: "Shout here" %>
  <%= form.submit "Shout!" %>
<% end %>
<div>
  <%= render @shouts %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shouter</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if signed_in? %>
      Welcome <%= current_user.email %>
      <%= link_to "Sign out", sign_out_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", sign_in_path %>
    <% end if %>

    <% flash.each do |key, value| -%>
      <div class="flash <%= key %>"><%= value %></div>
    <% end -%>

    <%= yield %>

  </body>
</html>

app/views/shouts/_shout.html.erb
<div>
  <%= content_tag_for(:div, shout) do %>
    <%= link_to shout.user_email, shout.user %>
    <%= shout.body %>
    <%= link_to time_ago_in_words(shout.created_at), shout %> ago
  <% end %>
</div>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<% if current_user.can_follow(@user) %>
  <%= button_to "Follow", user_following_relationships_path(@user) %>
<% end %>
<%= render @shouts %>

app/views/welcome/index.html.erb
<h1>Hellow World</h1>
<%= form_for(@user) do |form| %>
  <div>
    <%= form.email_field :email, placeholder: "Email address" %>
  </div>
  <div>
    <%= form.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= form.submit "Sign Up" %>
  </div>
<%end%>